//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class antigeno_viral
    {
        public string Lote_Asign_Anti { get; set; }
        public string T20 { get; set; }
        public string BSA { get; set; }
        public string Cod_Glicerol { get; set; }
        public string PBST_1X { get; set; }
        public Nullable<System.DateTime> Fecha_Preparacion { get; set; }
        public Nullable<System.DateTime> Fecha_Termina { get; set; }
        public string IgM { get; set; }
        public string EI { get; set; }
        public string IgG { get; set; }
        public string IgA { get; set; }
        public string Observaciones { get; set; }
    }
}
