//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class componentesvih
    {
        public string Componente { get; set; }
        public string Componente_Desc { get; set; }
        public Nullable<bool> Vironostika { get; set; }
        public Nullable<bool> Adaltis { get; set; }
    }
}
