//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class conjugado
    {
        public string NoLote_Conjugado { get; set; }
        public Nullable<int> Volumen { get; set; }
        public string NH4SO4 { get; set; }
        public string PBS1X { get; set; }
        public string CH3COONa { get; set; }
        public string CH3COOH { get; set; }
        public string Na2CO3 { get; set; }
        public string NaHCO3 { get; set; }
        public string PEROX { get; set; }
        public string NaJO4 { get; set; }
        public string NaHBO { get; set; }
        public string BSA { get; set; }
        public string GLIC { get; set; }
        public string MEMBR { get; set; }
        public Nullable<System.DateTime> Fecha_Preparacion { get; set; }
        public Nullable<System.DateTime> Fecha_Terminacion { get; set; }
    }
}
