//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class controles_igg
    {
        public string Cod_Asign_ContIgG { get; set; }
        public string Tipo_Control { get; set; }
        public Nullable<float> D_Optica { get; set; }
        public Nullable<int> Volumen { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Finalizacion { get; set; }
        public string Oservaciones { get; set; }
    }
}
