//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class datosprotocoloigmzika
    {
        public string ControlPos { get; set; }
        public string ControlNeg { get; set; }
        public string ControlRadPos { get; set; }
        public string ControlRadNeg { get; set; }
        public string LoteIgM { get; set; }
        public string LoteAntigeno { get; set; }
        public Nullable<System.DateTime> fechafijIGM { get; set; }
        public Nullable<float> VolUsadoIGM { get; set; }
        public string ProcH2O { get; set; }
        public string TipoEstudio { get; set; }
        public string Coatting { get; set; }
        public string PB { get; set; }
        public string TB { get; set; }
        public Nullable<System.DateTime> FB { get; set; }
        public Nullable<byte> TMPB { get; set; }
        public string TIMEB { get; set; }
        public string Conjugado { get; set; }
        public string Substrato { get; set; }
        public Nullable<float> TSubstrato { get; set; }
        public string SHN { get; set; }
        public string STOP { get; set; }
        public float Factor { get; set; }
        public float Factor2 { get; set; }
        public float ControlPosLI { get; set; }
        public float ControlPosLS { get; set; }
        public float ControlNegLI { get; set; }
        public float ControlNegLS { get; set; }
        public float ControlPosRadLI { get; set; }
        public float ControlPosRadLS { get; set; }
        public float ControlNegRadLI { get; set; }
        public float ControlNegRadLS { get; set; }
    }
}
