//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class datosprotocolozikabob
    {
        public string ControlMax { get; set; }
        public string ControlMin { get; set; }
        public string NS1 { get; set; }
        public string TipoEstudio { get; set; }
        public string Coatting { get; set; }
        public string PBS { get; set; }
        public string TB { get; set; }
        public string CodSustBloqueo { get; set; }
        public string ZKA { get; set; }
        public string SFA { get; set; }
        public string Substrato { get; set; }
        public Nullable<float> TSubstrato { get; set; }
    }
}
