//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class datosprotocolorotaviru
    {
        public string Codigo { get; set; }
        public string ProcH2O { get; set; }
        public Nullable<float> TIMES { get; set; }
        public string ControlPos { get; set; }
        public string ControlNeg { get; set; }
        public float ControlNegLI { get; set; }
        public float ControlNegLS { get; set; }
        public float ControlPosLI { get; set; }
        public float ControlPosLS { get; set; }
        public int idDatosProtocoloRV { get; set; }
    }
}
