//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class datosprotocolochik
    {
        public string ControlPos { get; set; }
        public string ControlNeg { get; set; }
        public string LoteIgM { get; set; }
        public string LoteAntigenoViral { get; set; }
        public string LoteAntigenoNormal { get; set; }
        public string GGLOB { get; set; }
        public Nullable<System.DateTime> fechafijGG { get; set; }
        public Nullable<float> VolUsado { get; set; }
        public string ProcH2O { get; set; }
        public string Coatting { get; set; }
        public string PB { get; set; }
        public string TB { get; set; }
        public Nullable<System.DateTime> FB { get; set; }
        public Nullable<byte> TMPB { get; set; }
        public string TIMEB { get; set; }
        public string Conjugado { get; set; }
        public string Substrato { get; set; }
        public Nullable<float> TSubstrato { get; set; }
        public string SHN { get; set; }
        public string STOP { get; set; }
        public string Tecnica { get; set; }
        public Nullable<float> LimCPI { get; set; }
        public Nullable<float> LimCPS { get; set; }
        public Nullable<float> LimCNI { get; set; }
        public Nullable<float> LimCNS { get; set; }
        public Nullable<float> FVC { get; set; }
    }
}
