//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class datosprotocolozikaigmbei
    {
        public string ControlPos { get; set; }
        public string ControlNeg { get; set; }
        public string AntiIgM { get; set; }
        public Nullable<System.DateTime> fechafijIGM { get; set; }
        public string TipoEstudio { get; set; }
        public string Coatting { get; set; }
        public string PBS { get; set; }
        public string TB { get; set; }
        public string CodSustBloqueo { get; set; }
        public string LoteAntigenoViral { get; set; }
        public string LoteAntigenoNormal { get; set; }
        public string Conjugado { get; set; }
        public string TipoDiluyente { get; set; }
        public string CodDiluyente { get; set; }
        public string Substrato { get; set; }
        public string STOP { get; set; }
    }
}
