//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class elisaiggrepeticione
    {
        public string Cod_Pozo { get; set; }
        public byte posicion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Placa { get; set; }
        public float Lectura { get; set; }
        public Nullable<float> m3men { get; set; }
        public string Unidades { get; set; }
        public string Resultado { get; set; }
        public string ControlPos { get; set; }
        public string ControlNeg { get; set; }
        public string ControlNegSal { get; set; }
        public string LoteIgG { get; set; }
        public string LoteAntigeno { get; set; }
        public string GGLOB { get; set; }
        public string Conjugado { get; set; }
        public string Substrato { get; set; }
        public Nullable<float> TSubstrato { get; set; }
        public string SHN { get; set; }
        public string STOP { get; set; }
        public Nullable<bool> Valido { get; set; }
        public string Lab1 { get; set; }
        public string Lab2 { get; set; }
        public Nullable<int> user { get; set; }
    
        public virtual laboratorista laboratorista { get; set; }
        public virtual usuario usuario { get; set; }
    }
}
