//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class gammaglobulina
    {
        public string Lote_Asign_Gamma1 { get; set; }
        public string Codigo_Mx { get; set; }
        public string PBS1X { get; set; }
        public string NH4SO4 { get; set; }
        public Nullable<int> Volumen { get; set; }
        public Nullable<float> Concen_Gamma { get; set; }
        public Nullable<System.DateTime> Fecha_Preparacion { get; set; }
        public Nullable<System.DateTime> Fecha_Terminacion { get; set; }
        public string Observaciones { get; set; }
    }
}
