//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class kit_elisa_rotaviru
    {
        public kit_elisa_rotaviru()
        {
            this.reactivos_rotavirus = new HashSet<reactivos_rotaviru>();
            this.rotavirus = new HashSet<rotaviru>();
        }
    
        public string Codigo { get; set; }
        public string Lote { get; set; }
        public string CasaComercial { get; set; }
        public string Metodo { get; set; }
    
        public virtual ICollection<reactivos_rotaviru> reactivos_rotavirus { get; set; }
        public virtual ICollection<rotaviru> rotavirus { get; set; }
    }
}
