//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class kit_elisa_vih
    {
        public kit_elisa_vih()
        {
            this.reactivos_vih = new HashSet<reactivos_vih>();
            this.vihs = new HashSet<vih>();
        }
    
        public string Codigo { get; set; }
        public string Lote { get; set; }
        public string CasaComercial { get; set; }
        public string Metodo { get; set; }
    
        public virtual ICollection<reactivos_vih> reactivos_vih { get; set; }
        public virtual ICollection<vih> vihs { get; set; }
    }
}
