//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ns1
    {
        public string Cod_Pozo { get; set; }
        public byte posicion { get; set; }
        public System.DateTime Fecha { get; set; }
        public string Placa { get; set; }
        public System.DateTime Hora { get; set; }
        public float Lectura { get; set; }
        public string Unidades { get; set; }
        public string Concen { get; set; }
        public string Resultado { get; set; }
        public float VC { get; set; }
        public string CodigoKit { get; set; }
        public Nullable<float> CalFactor { get; set; }
        public Nullable<byte> TIMES { get; set; }
        public string ProcH2O { get; set; }
        public string ControlPos { get; set; }
        public string ControlNeg { get; set; }
        public Nullable<bool> Valido { get; set; }
        public string Lab1 { get; set; }
        public string Lab2 { get; set; }
        public string User { get; set; }
        public Nullable<bool> Tras { get; set; }
    
        public virtual kit_elisa_ns1 kit_elisa_ns1 { get; set; }
    }
}
