//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class pbs1x
    {
        public string Lote_Asign_20X { get; set; }
        public Nullable<int> Numero { get; set; }
        public string Lote_Asign_1X { get; set; }
        public Nullable<int> Volumen { get; set; }
        public string H2ODEST { get; set; }
        public string Observaciones { get; set; }
    }
}
