//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class pbs20x
    {
        public string Lote_Asign_20X { get; set; }
        public Nullable<int> Volumen { get; set; }
        public string NaCl { get; set; }
        public string KCl { get; set; }
        public string KH2PO4 { get; set; }
        public string Na2HPO4 { get; set; }
        public string H2ODEST { get; set; }
        public string Observaciones { get; set; }
    }
}
