//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class ph_9_6__coatting_
    {
        public string Lote_Asign_Coatting { get; set; }
        public Nullable<int> Volumen { get; set; }
        public string Na2CO3 { get; set; }
        public string NaHCO3 { get; set; }
        public string H2ODEST { get; set; }
        public Nullable<float> pH { get; set; }
        public Nullable<System.DateTime> Fecha_Preparacion { get; set; }
        public Nullable<System.DateTime> Fecha_Expiracion { get; set; }
        public string Oservaciones { get; set; }
    }
}
