//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class reactivos_bei
    {
        public string Codigo { get; set; }
        public string Tipo { get; set; }
        public string Lote { get; set; }
        public string CasaComercial { get; set; }
        public string Titulo { get; set; }
        public string Concentracion { get; set; }
        public Nullable<System.DateTime> Fecha_Expiracion { get; set; }
        public Nullable<System.DateTime> Fecha_Inicio { get; set; }
        public Nullable<System.DateTime> Fecha_Finalizacion { get; set; }
        public string Oservaciones { get; set; }
    }
}
