//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class reactivos_vih
    {
        public string CodigoKit { get; set; }
        public string Componente { get; set; }
        public string CodigoC { get; set; }
        public string Lote { get; set; }
        public System.DateTime Fecha_Expiracion { get; set; }
        public string Observaciones { get; set; }
    
        public virtual kit_elisa_vih kit_elisa_vih { get; set; }
    }
}
