//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class substrato
    {
        public string Lote_Asign_TMB { get; set; }
        public string Lote { get; set; }
        public string Distribuidora { get; set; }
        public string Cod_Catalogo_TMB { get; set; }
        public Nullable<System.DateTime> Fecha_Inicia { get; set; }
        public Nullable<System.DateTime> Fecha_Termina { get; set; }
        public Nullable<System.DateTime> Fecha_Expiracion { get; set; }
        public Nullable<float> Vol_total { get; set; }
        public Nullable<float> Vol_Pozo { get; set; }
        public Nullable<int> Concentracion_Inc { get; set; }
        public Nullable<int> Concentracion_Uso { get; set; }
        public string Observaciones { get; set; }
    }
}
