//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ELISA
{
    using System;
    using System.Collections.Generic;
    
    public partial class tipo_control
    {
        public string Descripcion { get; set; }
        public Nullable<bool> EI { get; set; }
        public Nullable<bool> IgM { get; set; }
        public Nullable<bool> IgG { get; set; }
    }
}
